[package]
name = "brownie-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
brownie-protocol = { path = "../brownie-protocol" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true

[dev-dependencies]
base64.workspace = true
brownie-agentmodes = { path = "../brownie-agentmodes" }
brownie-modepack = { path = "../brownie-modepack" }
brownie-store = { path = "../brownie-store" }
ed25519-dalek.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "brownie"
path = "src/main.rs"
